version: 2.1
workflows:
  deployment-workflow:
    jobs:
      - tests:
      - build:
          name: 'build-dev'
          my_env : dev
          requires:
            - tests
          filters:
            branches:
              only: develop
      - build:
          name: 'build-uat'
          my_env : uat
          requires:
            - tests
          filters:
            branches:
              only: uat
      - build:
          name: 'build-prod'
          my_env : prod
          requires:
            - tests
          filters:
            branches:
              only: main
      - deploy:
          name: 'deploy-dev'
          my_env : dev
          requires:
            - build-dev
          filters:
            branches:
              only: develop
      - deploy:
          name: 'deploy-uat'
          my_env : uat
          requires:
            - build-uat
          filters:
            branches:
              only: uat
      - deploy:
          name: 'deploy-prod'
          my_env : prod
          requires:
            - build-prod
          filters:
            branches:
              only: main
jobs:
  tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
  build:
    parameters:
      my_env:
        description: "environment"
        default: "dev"
        type: string
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"

  deploy:
    parameters:
      my_env:
        description: "environment"
        default: "dev"
        type: string
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
