version: 2.1
parameters:
  pull_request:
    type: boolean
    default: false
workflows:
  pull_request:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - tests

  deployment-workflow:
    unless: << pipeline.parameters.pull_request >>
    jobs:
      - tests
      - build:
          name: 'build-dev'
          requires:
            - tests
          filters:
            branches:
              only: develop
      - build:
          name: 'build-uat'
          requires:
            - tests
          filters:
            branches:
              only: uat
      - build:
          name: 'build-prod'
          requires:
            - tests
          filters:
            branches:
              only: main
      - deploy:
          name: 'deploy-dev'
          requires:
            - build-dev
          filters:
            branches:
              only: develop
      - deploy:
          name: 'deploy-uat'
          requires:
            - build-uat
          filters:
            branches:
              only: uat
      - deploy:
          name: 'deploy-prod'
          requires:
            - build-prod
          filters:
            branches:
              only: main
jobs:
  tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}
