version: 2.1
parameters:
  pull_request:
    type: boolean
    default: false
workflows:

  # PR Tests 
  on-pull-request-tests:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - tests

  # feature,hotfix,bugfix Tests 
  on-push-tests:
    unless : << pipeline.parameters.pull_request >>
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - develop
                - uat
                - main
  # DEV 
  build-and-deployment-to-dev:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - build
      - deploy:
          requires:
            - build
  
  # UAT
  build-and-deployment-to-uat:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ uat, << pipeline.git.branch >> ]
    jobs:
      - build
      - deploy:
          requires:
            - build
  
  # PROD
  build-and-deployment-to-prod:
    when:
      and:
        - equal: [ false, << pipeline.parameters.pull_request >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build
      - deploy:
          requires:
            - build

  # Jobs definitions      
jobs:
  tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Branch ${CIRCLE_BRANCH}"
          command: echo ${CIRCLE_BRANCH}
