# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - uat
      - main
    types: [ opened]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-CircleCi:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        env: 
          CIRCLE_BRANCH: ${{ github.head_ref }}
          CIRCLE_BRANCH_TARGET: ${{ github.base_ref }}
        run: |
          curl -X POST \
          -H 'Circle-Token: ${{secrets.CIRCLE_TOKEN}}' \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d "{\"branch\":\"${CIRCLE_BRANCH}\",\"parameters\":{\"pull_request\":true,\"target_branch\":\"${CIRCLE_BRANCH_TARGET}\"}}" \
          https://circleci.com/api/v2/project/gh/hicham-mdous/deployment-demo/pipeline
          echo test, and deploy your project.
